
extern zend_class_entry *wxpay_api_micropay_createrefund_ce;

ZEPHIR_INIT_CLASS(WXPay_Api_Micropay_CreateRefund);

static zend_object_value zephir_init_properties_WXPay_Api_Micropay_CreateRefund(zend_class_entry *class_type TSRMLS_DC);

ZEPHIR_INIT_FUNCS(wxpay_api_micropay_createrefund_method_entry) {
	PHP_FE_END
};
